# Generated by Django 2.0.4 on 2020-02-11 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0002_auto_20200212_0209'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField()),
                ('time', models.CharField(max_length=20)),
                ('period', models.CharField(max_length=20)),
                ('school', models.CharField(max_length=30)),
                ('major', models.CharField(max_length=40)),
                ('college', models.CharField(max_length=40)),
                ('detail', models.TextField()),
            ],
            options={
                'ordering': ('-order',),
            },
        ),
    ]
