# Generated by Django 2.0.4 on 2020-02-11 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0003_education'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='basicinformation',
            options={'ordering': ('order',)},
        ),
        migrations.AlterModelOptions(
            name='education',
            options={'ordering': ('order',)},
        ),
    ]
