# Generated by Django 2.0.4 on 2020-02-12 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0004_auto_20200212_0228'),
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField()),
                ('type', models.CharField(max_length=20)),
                ('time', models.CharField(max_length=20, null=True)),
                ('period', models.CharField(max_length=20, null=True)),
                ('event', models.CharField(max_length=30, null=True)),
                ('title', models.CharField(max_length=40, null=True)),
                ('subtitle', models.CharField(max_length=40, null=True)),
                ('detail', models.TextField(null=True)),
            ],
            options={
                'ordering': ('order',),
            },
        ),
        migrations.DeleteModel(
            name='Education',
        ),
    ]
