# Generated by Django 2.0.4 on 2020-02-12 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0006_auto_20200212_2127'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='sector',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
