# Generated by Django 2.0.4 on 2020-02-12 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0007_experience_sector'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='experience',
            options={'ordering': ('type', 'order')},
        ),
    ]
